### PR TITLE
Add WDL scripts from forum

### PR DESCRIPTION
**Pull request by knoblett**
This pull request is for #39 

Upload the following scripts:
- [x] jointCallingGenotypes
- [x] simpleVariantSelection
- [x] simpleVariantDiscovery
- [x] helloHaplotypeCaller

### CODE REVIEW

**Comment by knoblett** [comment]
@vdauwera I've uploaded the scripts. Let me know if there is anything else needed, otherwise I will rebase and merge. 
I think these are the right commands, assuming I execute from the directory of the wdl repo clone on my local machine. I recall wdl using develop in place of master.
```
git checkout knoblett-forumWdls
git fetch origin
git rebase -i origin/develop
git push -f
```

**Comment by vdauwera** [comment]
Looks great! Yes, the commands look correct.

**Comment by knoblett** [comment]
I've rebased; can I merge, or do I need to wait for the code-review/pullapprove? I seem to remember that we don't need it if merging to this directory, but I'd like to be sure.

**Comment by vdauwera** [comment]
You can merge it yourself, but first I would recommend renaming your commit and editing the commit message to be more representative of what it contains -- since right now it's just the name of the first commit you originally made. Do you know how to do that? (hint: one easy way is to use an option in rebase)

**Comment by knoblett** [comment]
Changed the message to be more descriptive. Merging now.

**Pull request merged**
