### PR TITLE
Add the production WDL for the GOTC single-sample pipeline

### PR DESCRIPTION
**Pull request by vdauwera**
This adds a directory structure for scripts + the two public Broad pipelines we have so far. Still need to run a few checks before merging.

Seeking comments on the directory names + how do we provide accompanying documentation and data resources for running/testing the scripts.

### CODE REVIEW

**Comment by kcibul** [comment]
Hey @vdauwera -- what's the next step on this?  Green Team to review for WDL conventions?

**Comment by vdauwera** [comment]
Hi @kcibul,

This is copied straight for dsde-pipelines so shouldn't need any code review as such (although it would be great to have a test environment to check that this actually runs, since I made a few subtractions). 

What's really missing is documentation and a versioning system. On the docs side I'm going to write a readme to accompany the pipeline scripts -- I'm the blocker on that front, just need to take half an hour to hammer out something reasonable. On the versioning side -- I need to be able to give users a version number that refers to a particular version that we use in production. But my understanding is that production doesn't currently *have* a straightforward version numbering scheme for the pipelines (happy to learn if I'm wrong). I was planning to bring that up at the next leads meeting but if you have any thoughts on that I'd love to hear them.

**Comment by vdauwera** [comment]
Update: we now have a shiny new public version of the single-sample WDL with more documentation, including pipeline requirements. Versioning still done with datestamp for now, but green team has a plan for tag-based versioning (hooray).

Also including a directory structure for WDL scripts.

Still to come: README for the scripts directory, json of inputs for the pipeline WDL and more info on accessing the dockers + their contents.

**Comment by vdauwera** [comment]
@geoffjentry Is `develop` the de facto master branch here? I'm used to `master` being master...

**Comment by vdauwera** [comment]
The WDL itself has already been reviewed, tested and thumbsupped so this shouldn't require code review. Please let me know if I can go ahead and merge or if you want to discuss this further, @kcibul / @geoffjentry.

**Comment by bradtaylor** [comment]
The docker broadinstitute/genomes-in-the-cloud is not public, and there are issues with making is public. So this WDL will not be functional to all users if distributed publicly. @kcibul and @vdauwera, I feel like we need to talk briefly in person about this issues.

**Comment by vdauwera** [comment]
@bradtaylor Happy to do a hangout at your convenience (I'm WFH with baby). FYI this is meant to be provided as a reference implementation, not a plug and play solution (yet). I can document that more clearly if that's the main issue.

**Comment by vdauwera** [comment]
All blockers resolved.

**Pull request merged**
