### PR TITLE
Point at the official website

### PR DESCRIPTION
**Pull request by geoffjentry**

### CODE REVIEW

**Comment by geoffjentry** [comment]
@scottfrazer @knoblett can you two check this out?

**Comment by scottfrazer** [comment]
uhh I didn't think we were gutting the whole entire thing...  those are good examples which just need a little bit of updating!  It'd be a shame to lose them entirely... and also the website doesn't (yet) entirely cover these examples.  For example, I was unable to find an example that used a `read_int` function

If we're going to remove them from this README, can we make sure all concepts are exercised in these examples are also on the web site in some form?

**Comment by vdauwera** [comment]
Oof that does seem a bit extreme. I would recommend copying that content to a separate document that is labeled as a developer-oriented resource.

**Comment by geoffjentry** [comment]
@scottfrazer The gutting part is what I was asking about earlier, not updating them. I think the less overlap we have with the website the better - @vdauwera @knoblett can we get richer examples on the website at some point in the not too distant future?

**Comment by vdauwera** [comment]
Certainly we can plan to add examples to cover all of this on the website -- how about creating issues to that effect in this repo?

**Comment by geoffjentry** [comment]
@vdauwera All of it or just the stuff which doesn't overlap with the site? The fact that we have this issue here demonstrates the pain of having the same effective stuff in multiple places

**Comment by geoffjentry** [comment]
@vdauwera my last comment was in response to your comment prior to the issue filing btw.

**Comment by vdauwera** [comment]
@geoffjentry Yep, got that. I'm reluctant to get rid of any of that content right away because I wonder if it might be useful as an orthogonal approach aimed at developers. I'd like to keep it in the back pocket until we've had a chance to get more feedback on how different types of people feel about the website content and presentation.

**Comment by vdauwera** [comment]
So I guess I'm saying, keep the whole thing on the side for now, with the possibility of removing it entirely a few months down the road.

**Comment by scottfrazer** [comment]
Well sorry I misunderstood you... I don't think we should remove these until the web site covers these concepts sufficiently... I know that people have used and liked these examples!  It'd be a shame to remove them with only a promise that eventually they'll be added to the web site again... I'll very gladly fix these docs this weekend if that's what it'll take

**Comment by geoffjentry** [comment]
@vdauwera I was hoping to avoid having to actually fix what's broken in there, doh ;) I'll close this for now, may or may not get around to fixing the examples & moving them

**Comment by vdauwera** [comment]
Well it would still be good to add the reference to the website (the first paragraph you added) and maybe state explicitly that there are these two types of docs -- say "read on for a developer-oriented quick-start doc, or head over to the website for more hand-holding"

**Pull request closed without merging**
