### PR TITLE
document at length.  Closes broadinstitute/cromwell#1604

### PR DESCRIPTION
**Pull request by mcovarr**

### CODE REVIEW

**Comment by cjllanwarne** [comment]
👍

**Comment by vdauwera** [comment]
👍

**Comment by vdauwera** [comment]
@geoffjentry I humbly suggest adding me to the pullapprove list

**Comment by geoffjentry** [comment]
@vdauwera I have humbly done so, it doesn't look to be retroactive so I'll give a :+1: for ya

**Comment by vdauwera** [comment]
Many thanks, good sir

**Pull request merged**
