### PR TITLE
Update highlighter readme

### PR DESCRIPTION
**Pull request by vdauwera**
There is no AAAPackageDev (anymore?) but changing to PackageDev works.

### CODE REVIEW

**Comment by vdauwera** [comment]
@geoffjentry Any objections to this change? I think the instructions were out of date.

**Comment by geoffjentry** [comment]
If it works, sure. I have *no* idea about how this stuff works

**Comment by vdauwera** [comment]
Hmm just realized this is set to go into master, not develop. Will reopen against develop.

**Comment by vdauwera** [comment]
Oh. It was correct in develop. *sigh*

**Pull request closed without merging**
